version: "3"
services:
  web:
    image: pgrabolosa/kitura
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: toto
      MYSQL_USER_NAME: root
      MYSQL_USER_PASSWORD: toto
      MYSQL_DATABASE: mydb
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toto
      MYSQL_DATABASE: mydb
